baseURL = "https://zephiransas.github.io/"
disablePathToLower = "true"
languageCode = "ja"
title = "zephiransasのチラシの裏"
theme = "bleak"

[params]
  # Warning Keys are case sensitives
  Subtitle = "とあるプログラマのメモ代わりブログ"

  [params.author]
    twitter = "zephiransas"
