baseURL = "https://zephiransas.github.io/"
disablePathToLower = "true"
languageCode = "ja"
title = "zephiransasのチラシの裏"
theme = "bleak"
# buildFuture = true

[params]
  # Warning Keys are case sensitives
  Subtitle = "とあるプログラマのメモ代わりブログ"
  logo = '/images/zephiransas.jpeg'

  [params.author]
    twitter = "zephiransas"
